/**
 * Regenerate src/lib/brand/logo.ts from the bundled logo asset.
 *
 * The logo is inlined as a base64 data URI so it works in two contexts where a
 * normal asset URL would fail:
 *   1. The Canvas social posters — a data-URI image is same-origin/untainted, so
 *      `canvas.toBlob()` (the PNG download) keeps working.
 *   2. The print/PDF documents — they open in a `blob:` window where relative
 *      paths don't resolve, so the logo must be embedded in the HTML.
 *
 * Run:  node scripts/encode-logo.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const SRC = resolve(root, "src/assets/cotrackpro-logo.jpg");
const OUT = resolve(root, "src/lib/brand/logo.ts");

const base64 = readFileSync(SRC).toString("base64");
const dataUri = `data:image/jpeg;base64,${base64}`;

const file = `/** AUTO-GENERATED by scripts/encode-logo.mjs — do not edit by hand.
 *  The CoTrackPro logo, inlined as a base64 data URI so it renders on the
 *  Canvas share posters (no cross-origin taint) and inside the print/PDF
 *  blob documents (no network, no unresolved relative paths). */
export const LOGO_DATA_URI =
  "${dataUri}";
`;

writeFileSync(OUT, file);
console.log(`Wrote ${OUT} (${base64.length} base64 chars from ${SRC})`);
